#!/usr/bin/env bash

#pkg="$(ls ~/.local/source/void-packages/srcpkgs | dmenu -i -fn Hermit:size=10 -nb '#222222' -sb '#007687' -sf '#222222' -nf '#b8b8b8' -l 10 -g 7 -p "What would you like to install? :")"
pkg="$(ls ~/.local/source/void-packages/srcpkgs | fzf --border=rounded --margin=1% --color=dark --color='pointer:12,bg+:8' --height 100% --reverse --no-scrollbar --info=hidden --header-first --prompt "  the void files   ")"
DIR1=$HOME/.local/source/void-packages/
DIR2=$HOME/.local/source/void-packages/srcpkgs
CHECK="$(xbps-query -s "$pkg" | wc -l)"


if [ "$pkg" ]
then
    if [ "$CHECK" -eq "1" ]
    then
        notify-send "You are good to go, program already installed! have a wonderful day, gorgeous!"
        sleep 2
        exit
    else
        cd "$DIR1" || exit
        git pull

        cd "$DIR2" || exit
        if [[ -d "$pkg" ]]
        then
            cd "$DIR1" || exit
            notify-send -t 60000 "installing $pkg, Please be patient" 
            ./xbps-src pkg "$pkg" && sudo xbps-install -Sy --repository hostdir/binpkgs "$pkg" 
        else
            notify-send "Not found"
            exit
        fi
    fi
else
    exit
fi
notify-send "$pkg installed"
