#!/bin/dash

term=kitty
edit=nvim


#dest=$(sed -e 's/\s*#.*//' -e '/^$/d' -e 's/^\S*\s*//' /home/jgr/.local/bm-config | fzf --reverse --header='choose a config: ' | sed 's|~|$HOME|')
#dest=$(grep -v '^#' ~/.local/bm-config | rofi -dmenu -p 'choose a config: ' | cut -d'*' -f2)
dest=$(grep -v '^#' ~/.local/bm-config | fzf | cut -d'*' -f2)


if [ -z $dest ]; then
    echo "no selection"
    exit
fi


devour kitty -e $edit $dest
