#!/bin/dash

chosen=$(cut -d ';' -f1 ~/.local/share/icons/myicons/* | dmenu -f -i -p "😑 icons" | sed "s/ .*//")

# Exit if none chosen.
[ -z "$chosen" ] && exit

if [ -n "$1" ]; then
	xdotool type "$chosen"
else
	printf "%s" "$chosen" | xclip -selection clipboard
	notify-send "'$chosen' copied to clipboard." &
fi
