#!/bin/dash

ff () { xdg-open $(find -type f |  fzf --preview "bat --color always --style=plain {1}" --preview-window=:hidden --bind=space:toggle-preview --border=rounded --margin=1% --color=dark --color='pointer:12,bg+:8' --height 100% --reverse --no-scrollbar --header='find file ' --info=inline-right --header-first --prompt " "
    ) ;clear ;}
    #fzf --preview 'bat --color always {1}' 

