#!/bin/dash

fj() { cd $(find -type d | fzf --border=rounded --margin=1% --color=dark --color='pointer:12,bg+:8' --height 100% --reverse --no-scrollbar --header='jump to ' --info=inline-right --header-first --prompt " ") ;clear ;ls ;}
