#!/bin/dash

menu(){
    printf "lock\n"
    printf "sleep\n"
    printf "shutdown\n"
    printf "reboot\n"
    printf "exitx\n"
}

main(){
    choice=$(menu | rofi -p " 󰚩  " -dmenu)

    case $choice in
        lock)
            betterlockscreen -l blur
            ;;
        sleep)
            systemctl suspend
            ;;
        shutdown)
            shutdown now
            ;;
        reboot)
            reboot
            ;;
        exitx)
            loginctl terminate-session ${XDG_SESSION_ID-}
            ;;
        *)
            exit 1
            ;;
        esac
    }

    main


