#!/bin/dash

handle_default() {
    if [ ! -z "$1" ]; then
        devour "$1" "$url"
    elif [ ! -z "$BROWSER" ]; then
        devour "$BROWSER" "$url"
    fi
}

url=$(sort ~/.local/bookmarks | awk '{gsub(/#.*/, ""); print}' | fzf --border=rounded --margin=1% --color=dark --color='pointer:12,bg+:8' --height 100% --reverse --no-scrollbar --header='bookmarks ' --info=hidden --header-first --prompt " " | awk '{system("grep "$1" ~/.local/bookmarks")}' | sed 's/.*#//')

if [ $url ]; then
    case "$1" in
        xdo) xdotool selectwindow type "$url" ;;
        *) handle_default ;;
    esac
fi
