#!/bin/dash

xrandr --output DP-0 --mode 2560x1440 --rate 165 --primary --output HDMI-1 --mode 1920x1080 --rate 144 --left-of DP-0 --dpi 130

setxkbmap no

xset r rate 155 70 

xset s off -dpms

redshift -PO 3500

dunst &

unclutter -idle 2 &

picom --no-fading-openclose --legacy-backends &

~/.fehbg &
# feh --bg-fill --randomize ~/disk2/pictures/fav* --bg-fill --randomize ~/disk2/pictures/fav* &

dbus-run-session pipewire &

mpd &

[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

###########
#dwmstuff
###########

 Statusbar loop
while true; do
   xsetroot -name "$( date +"%a %d %b | %R" )"
   sleep 1m    # Update time every minute
done &

#sxhkd -c ~/.config/bspwm/sxhkdrc &

exec dbus-run-session -- dwm
