#!/bin/sh

menu(){
    printf "youtube\n"
    printf "bravesearch\n"
    printf "netflix\n"
    printf "protonmail\n"
    printf "gmail\n"
    printf "oryxmoonlander\n"
    printf "github\n"
}

choice="$(menu | dmenu -f -i -p " browser" | cut -d' ' -f1)"

case "$choice" in
    youtube)
        choice="https://www.youtube.com"
        ;;
    bravesearch)
        choice='https://search.brave.com/'
        ;;
    netflix)
        choice='https://www.netflix.com/browse'
        ;;
    protonmail)
        choice='https://mail.proton.me/u/2/inbox'
        ;;
    gmail)
        choice='https://mail.google.com/mail/u/0/#inbox'
        ;;
    oryxmoonlander)
        choice='https://configure.zsa.io/moonlander/layouts/0pLP4/latest/0'
        ;;
    github)
        choice='https://github.com/'
        ;;
    *)
        exit 1
        ;;
esac
$BROWSER "$choice"



