#!/bin/sh

wallpaper1=$(ls ~/disk2/pictures/wallpapers | dmenu -f -i -p "wallpaper 1");
wallpaper2=$(ls ~/disk2/pictures/wallpapers | dmenu -f -i -p "wallpaper 2");

[ $wallpaper1 -z ] || feh --bg-fill /home/jgrvoid/disk2/pictures/wallpapers/$wallpaper1 /home/jgrvoid/disk2/pictures/wallpapers/$wallpaper2
