#!/bin/sh

menu(){
    printf "1.  one\n"
    printf "2.  two\n"
    printf "3.  three\n"
    printf "4.  four\n"
    printf "5.  five\n"
    printf "6.  six\n"
    printf "7.  seven\n"
    printf "8.  eight\n"
    printf "9.  discord\n"
    printf "10. chat/steam\n"
}

choice=$(menu | rofi -matching fuzzy -dmenu -i -p "🐦send" -selected-row 1 | cut -d. -f1)

case $choice in
    1)
        dkcmd ws send 1
        ;;
    2)
        dkcmd ws send 2
        ;;
    3)
        dkcmd ws send 3
        ;;
    4)
        dkcmd ws send 4
        ;;
    5)
        dkcmd ws send 5
        ;;
    6)
        dkcmd ws send 6
        ;;
    7)
        dkcmd ws send 7
        ;;
    8)
        dkcmd ws send 8
        ;;
    9)
        dkcmd ws send 9
        ;;
    10)
        dkcmd ws send 10
        ;;

    esac




