#!/bin/sh

menu(){
    printf "4.  four\n"
    printf "5.  five\n"
    printf "6.  six\n"
    printf "7.  seven\n"
    printf "8.  eight\n"
    printf "9.  discord\n"
    printf "10. chat/steam\n"
}

choice=$(menu | rofi -matching fuzzy -dmenu -i -p "🐈view" -selected-row 6 | cut -d. -f1)

case $choice in
    4)
        dkcmd ws view 4
        ;;
    5)
        dkcmd ws view 5
        ;;
    6)
        dkcmd ws view 6
        ;;
    7)
        dkcmd ws view 7
        ;;
    8)
        dkcmd ws view 8
        ;;
    9)
        dkcmd ws view 9
        ;;
    10)
        dkcmd ws view 10
        ;;

    esac




