#!/bin/sh

term=alacritty
editor=nvim

menu(){
    printf "bookmarks\n"
    printf "sxhkdrc\n"
    printf "bspwmrc\n"
    printf "browserstart\n"
    printf "newsboaturl\n"
    printf "rofconfigs\n"
}

choice="$(menu | rofi -matching fuzzy -dmenu -i -p "  configs")"

case "$choice" in
    bookmarks)
        choice="$HOME/.local/bookmarks"
        ;;
    sxhkdrc)
        choice="$HOME/.config/bspwm/sxhkdrc"
        ;;
    bspwmrc)
        choice="$HOME/.config/bspwm/bspwmrc"
        ;;
    bs)
        choice="$HOME/.local/bin/scripts/rofibrowserstart"
        ;;
    nb)
        choice="$HOME/.config/newsboat/urls"
        ;;
    roficonfigs)
        choice="$HOME/.local/bin/scripts/roficonfigs"
        ;;
    *)
        exit 1
        ;;
    esac
$term -e $editor $choice
