#!/bin/sh

term=alacritty
editor=nvim

menu(){
    printf "bookmarks\n"
    printf "browserstart\n"
    printf "newsboaturl\n"
    printf "roficonfigs\n"
}

choice="$(menu | rofi -matching fuzzy -dmenu -i -p "  configs")"

case "$choice" in
    bookmarks)
        choice="$HOME/.local/bookmarks"
        ;;
    browserstart)
        choice="$HOME/.local/share/scripts/rofi/rofibrowser"
        ;;
    newsboaturl)
        choice="$HOME/.config/newsboat/urls"
        ;;
    roficonfigs)
        choice="$HOME/.local/share/scripts/rofi/roficonfigs"
        ;;
    *)
        exit 1
        ;;
    esac
$term -e $editor $choice
