#!/bin/sh

wallpaper1=$(ls ~/disk2/pictures/fav | rofi -matching fuzzy -dmenu -i -p "wallpaper 1");
wallpaper2=$(ls ~/disk2/pictures/fav | rofi -matching fuzzy -dmenu -i -p "wallpaper 2");

[ $wallpaper1 -z ] || feh --bg-fill /home/jgrvoid/disk2/pictures/fav/$wallpaper1 /home/jgrvoid/disk2/pictures/fav/$wallpaper2
