#!/bin/sh 

menu(){
    printf "brave search\n"
    printf "flathub\n"
    printf "protondb\n"
    printf "youtube\n"
    printf "archwiki\n"
}

choice="$(menu | rofi -matching fuzzy -dmenu -i -p "  engine" | cut -d' ' -f1)"
q="$(rofi -dmenu -p "search wat ever u want m8")"

case "$choice" in
    brave)
        choice="https://search.brave.com/search?q=$q&source=web"
        ;;
    flathub)
        choice="https://flathub.org/apps/search?q=$q"
        ;;
    protondb)
        choice="https://www.protondb.com/search?q=$q"
        ;;
    youtube)
        choice="https://www.youtube.com/results?search_query=$q"
        ;;
    archwiki)
        choice="https://wiki.archlinux.org/index.php?search=$q"
        ;;
    *)
        exit 1
        ;;
esac

if [ "$q" ]
then
    $BROWSER "$choice"
else
    exit 1
fi


