#!/bin/sh

menu(){
    printf "4. four\n"
    printf "5. five\n"
}

choice=$(menu | rofi -matching fuzzy -dmenu -f -i -p "🐈view" | cut -d. -f1)

case $choice in
    4)
        dwmc viewex 3
        ;;
    5)
        dwmc viewex 4
        ;;

    esac




