#!/bin/sh

menu(){
    printf "4.  four\n"
    printf "5.  five\n"
    printf "6.  six\n"
    printf "7.  seven\n"
    printf "8.  eight\n"
    printf "9.  discord\n"
    printf "10. chat/steam\n"
}

choice=$(menu | rofi -matching fuzzy -dmenu -i -p "🐈view" -selected-row 6 | cut -d. -f1)

case $choice in
    4)
        bspc desktop -f ^4
        ;;
    5)
        bspc desktop -f ^5
        ;;
    6)
        bspc desktop -f ^6
        ;;
    7)
        bspc desktop -f ^7
        ;;
    8)
        bspc desktop -f ^8
        ;;
    9)
        bspc desktop -f ^9
        ;;
    10)
        bspc desktop -f ^10
        ;;

    esac




