#!/bin/sh

menu(){
    printf "lock\n"
    printf "sleep\n"
    printf "shutdown\n"
    printf "reboot\n"
    printf "exitx\n"
}

main(){
    choice="$(menu | rofi -matching fuzzy -dmenu -i -p "󰚩 system")"

    case "$choice" in
        lock)
            slock
            ;;
        sleep)
            loginctl suspend
            ;;
        shutdown)
            loginctl poweroff
            ;;
        reboot)
            loginctl reboot
            ;;
        exitx)
            pkill -u jgrvoid
            ;;
        *)
            exit 1
            ;;
    esac
}

main


