#!/bin/sh

menu(){
    printf "4.  steam\n"
    printf "5.  five\n"
    printf "6.  six\n"
    printf "7.  chat\n"
}

choice=$(menu | rofi -matching fuzzy -dmenu -i -p "🐈view" | cut -d. -f1)

case $choice in
    4)
        bspc desktop -f ^4
        ;;
    5)
        bspc desktop -f ^5
        ;;
    6)
        bspc desktop -f ^6
        ;;
    7)
        bspc desktop -f ^7
        ;;

    esac




