#!/bin/sh

pgrep -x rofi && exit

mountable=$(lsblk -lp | grep "part $" | awk '{print $1, "(" $4 ")"}')
[ "$mountable" = "" ] && exit 1
chosen=$(echo "$mountable" | rofi -matching fuzzy -dmenu -i -p "💿 what to mount tho" | awk '{print $1}')
[ "$chosen" = "" ] && exit 1
udisksctl mount -b $chosen && pgrep -x dunst && notify-send "$chosen mounted"
