#!/bin/sh

menu(){
    printf "youtube\n"
    printf "brave search\n"
    printf "netflix\n"
    printf "moonlander zsa oryx\n"
    printf "github\n"
    printf "monkeytype\n"
}

choice="$(menu | rofi -matching fuzzy -dmenu -i -p " browser" | cut -d' ' -f1)"

case "$choice" in
    youtube)
        choice="https://www.youtube.com"
        ;;
    brave)
        choice='https://search.brave.com/'
        ;;
    netflix)
        choice='https://www.netflix.com/browse'
        ;;
    moonlander)
        choice='https://configure.zsa.io/moonlander/layouts/0pLP4/latest/0'
        ;;
    github)
        choice='https://github.com/'
        ;;
    monkeytype)
        choice='https://monkeytype.com/'
        ;;
    *)
        exit 1
        ;;
esac
$BROWSER "$choice"



