#! /bin/dash

 #    #    #
# # j g r # #
 #    #    #

## Fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1
wmname LG3D

#monitor
bspc wm -O DP-0 HDMI-1
bspc monitor DP-0 -d 1 2 3 steam
bspc monitor HDMI-1 -d 4 5 6 chat


#configuration
bspc config border_width            4
bspc config window_gap              12
spc config top_padding              0
bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config paddingless_monocle     true
bspc config single_monocle          false
bspc config automatic_scheme        longest_side
bspc config initial_polarity        second_child

bspc config focus_follows_pointer   true
bspc config pointer_follows_focus   false
bspc config pointer_modifier        shift
bspc config pointer_action1         move
bspc config pointer_action2         resize_side
bspc config pointer_action3         resize_corner

#colors
bspc config normal_border_color   "#303446"
bspc config active_border_color   "#303446"
bspc config focused_border_color  "#769bd8"
bspc config presel_feedback_color "#FF4971"
bspc config urgent_border_color   "#d5a4b5"


#bspc rules
bspc rule -r *:*
bspc rule -a scpad sticky=on state=floating follow=on focus=on rectangle=1255x680+7+391
bspc rule -a scmusic sticky=on state=floating follow=on focus=on rectangle=1255x680+7+391
bspc rule -a discord desktop='chat' follow=off 
bspc rule -a steam desktop='steam' follow=off
bspc rule -a mpv state=fullscreen focus=on
bspc rule -a feh state=floating focus=on rectangle=1280x720
