#!/bin/sh

xrandr --output DP-0 --mode 2560x1440 --rate 165 --primary --output HDMI-1 --mode 1920x1080 --rate 144 --left-of DP-0 --dpi 100

setxkbmap no

xset r rate 230 40

redshift -PO 3500

dunst &

clipmenud &

unclutter -idle 2 &

picom --no-fading-openclose --legacy-backends &

~/.fehbg &

~/.config/polybar/polybarlaunch.sh


