#!/bin/sh

case "$1" in

    scratchpad) 		
        entry="alacritty --class scpad --title scratchpad -o font_size=18" 		
        ;;
    music)
        entry="alacritty --class scpad --title music -o font_size=18 -e ncmpcpp"
        ;;
    tox)
        entry="alacritty --class scpad --title tox -o font_size=18 -e toxic"
        ;;
    index)
        entry="alacritty --class scpad --title index -o font_size=18 -e neorgindex"
        ;;
esac

xdotool search --onlyvisible --name "$1" windowunmap \
    || xdotool search --name "$1" windowmap \
    || $entry &

